version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=${TZ}
    ports:
      - "1880:1880"
    volumes:
      - ./home-assistant/node-red/data:/data
  
  esphome:
    container_name: esphome
    image: esphome/esphome
    environment:
      - TZ=${TZ}
    volumes:
      - ./home-assistant/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports:
      - "6052:6052"
      - "6123:6123"